### ISSUE TITLE
Latest update broke integration

### ISSUE THREAD

**Issue by j6s33m** [cdnninja/yoto_ha#54]
No longer will connect. Continue to get "Failed Setup, will retry" message.

**Comment by cdnninja** [comment]
1.10.4?  What is the error in the logs?

**Comment by j6s33m** [comment]
![Screenshot 2024-05-21 214132](https://github.com/cdnninja/yoto_ha/assets/17929290/265a69d8-a85c-4130-9e7f-7df3928fa068)

**Comment by cdnninja** [comment]
What version?

**Comment by cjb0001** [comment]
```
  File "/config/custom_components/yoto/sensor.py", line 50, in <module>
    native_unit_of_measurement=UnitOfTemperature.LIGHT_LUX,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UnitOfTemperature' has no attribute 'LIGHT_LUX'
```
[https://www.home-assistant.io/integrations/sensor#device-class](https://www.home-assistant.io/integrations/sensor#device-class
)
The device class should be `illuminance`

**Comment by j6s33m** [comment]
> What version? 

1.10.4

HA v.2024.5.4

**Comment by cjb0001** [comment]
I just sent a PR which will fix this

**Comment by cdnninja** [comment]
I don't see the pr.  Could you double check?

**Comment by cjb0001** [comment]
fixed and sent

**Comment by cdnninja** [comment]
Should be good now.   let me know if not the case. Thanks all!

**Comment by j6s33m** [comment]
HA not showing an update yet for Yoto.

**Comment by cdnninja** [comment]
Go into HACS and update information.

**Comment by j6s33m** [comment]
It did not fix the problem. The integration is still broken, unfortunately.

**Comment by cdnninja** [comment]
What version is installed now? Any errors in logs?

**Comment by cdnninja** [comment]
Text version of logs would also help so I can format the payload and try run it locally.

**Comment by cjb0001** [comment]
1.10.6 is working fine for me.

@j6s33m try clicking Update Information from the three dots on the Yoto integration in HACS again...

![image](https://github.com/cdnninja/yoto_ha/assets/102877399/3a35ce8f-d262-4481-b4cb-119e2f9c5cf6)

**Comment by j6s33m** [comment]
That's what I did. Still can't log back in to integration. I've deleted, reinstalled the latest version and restarted HA.

**Comment by cdnninja** [comment]
Logs will help me with this.

**Comment by j6s33m** [comment]
Can't get you logs because I can't log in to turn them on. When the new release didn't work, i deleted the app and remove all folders/HACS connections to it. I've since reloaded it and cannot sign into your app at all. I can log in to the Yoto official app fine, but your home assistant integration gives me this error.

![Screenshot 2024-05-23 210414](https://github.com/cdnninja/yoto_ha/assets/17929290/61cbabb7-7d9b-4d97-8251-7321df015973)

**Comment by cdnninja** [comment]
The readme mentions how to enable debug logs manually.  

As well I would expect an error in logs regardless since you can't login now.

**Comment by cdnninja** [comment]
Please also roll back to the last version that worked and let me know the version number.

**Comment by j6s33m** [comment]
Nothing. I run HA in a docker container on my NAS. Zero power source issues.

**Comment by cdnninja** [comment]
Sorry I meant the yoto.  Were they plugged in or battery?

**Comment by j6s33m** [comment]
Edited my initial response to include the yotos as well. Everything is on and powered

**Comment by cdnninja** [comment]
New release is out to fix the above error. 1.10.9.

**Comment by j6s33m** [comment]
You fixed it! Thanks!

**Comment by cdnninja** [comment]
Great!  Glad to hear! I saw you had two yotos. I'm interested if both get real time card playing updates or not. Someone else reported only one does. Not the second.  Wanting to confirm if widespread issue with two devices or not.

**Comment by j6s33m** [comment]
Will have to test for you early next week. Won't be around this weekend. 

Thank you again. Appreciate all the work you are doing to build this out. The progress is amazing.

**Comment by cdnninja** [comment]
Okay I will close for now since other issues exist for that.
